# Starship configurations

# Inserts a blank line between shell prompts
add_newline = true

# Zephyr/NCS have many files
scan_timeout = 100

[[battery.display]]
threshold = 30
style = 'bold red'

[c]
disabled = true

[cmake]
disabled = true

[git_branch]
style = 'bold blue'

[git_status]
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕ ⇡${ahead_count} ⇣${behind_count}'

[python]
format = '[${symbol}${version} (\($virtualenv\) )]($style)'
python_binary = ['python3']
style = 'purple bold'
